### ISSUE TITLE
I want to get the appendix of this article, where can I find it

### ISSUE THREAD

**Issue by 1907040518** [THU-LYJ-Lab/AR-Seg#11]
I want to get the appendix of this article, where can I find it.

**Comment by AlbertHuyb** [comment]
You could find it in this CVPR html page: https://openaccess.thecvf.com/content/CVPR2023/html/Hu_Efficient_Semantic_Segmentation_by_Altering_Resolutions_for_Compressed_Videos_CVPR_2023_paper.html
