### ISSUE TITLE
ModuleNotFoundError: No module named 'localAttention'

### ISSUE THREAD

**Issue by Gchang9** [THU-LYJ-Lab/AR-Seg#2]
你好，model/attention.py里缺少localAttention模块

**Comment by AlbertHuyb** [comment]
Did you install the requirements following `requirements.txt` ?
The `localAttention` denpendency is included in `git+https://github.com/zzd1992/Image-Local-Attention.git@master`.
After install this dependency, you can import those functions.

Remember to firstly `import torch` before import from `localAttention` to include `libc10.so` library from `import torch`.

**Comment by AlbertHuyb** [comment]
I'm going to close this issue. Welcome to star this repo if you find it helpful.

**Comment by Yuziyi1117** [comment]
> Did you install the requirements following `requirements.txt` ? The `localAttention` denpendency is included in `git+https://github.com/zzd1992/Image-Local-Attention.git@master`. After install this dependency, you can import those functions.
> 
> Remember to firstly `import torch` before import from `localAttention` to include `libc10.so` library from `import torch`.
hi, 
I clone git+https://github.com/zzd1992/Image-Local-Attention,and install this dependency,but I still can't import this function,ModuleNotFoundError: No module named 'localAttention'. Please help me how to fix it . thanks

**Comment by Yuziyi1117** [comment]
> Did you install the requirements following `requirements.txt` ? The `localAttention` denpendency is included in `git+https://github.com/zzd1992/Image-Local-Attention.git@master`. After install this dependency, you can import those functions.
> 
> Remember to firstly `import torch` before import from `localAttention` to include `libc10.so` library from `import torch`.

hi,
I clone git+https://github.com/zzd1992/Image-Local-Attention,and install this dependency,but I still can't import this function,ModuleNotFoundError: No module named 'localAttention'. Please help me how to fix it . thanks
@AlbertHuyb

**Comment by AlbertHuyb** [comment]
@Yuziyi1117 
Thanks for your interest!
I've just tried once more and it works.
Could you please provide more information about your installation steps, e.g., screenshots, errors or logs ?
