### ISSUE TITLE
`dataset` is missing?

### ISSUE THREAD

**Issue by tongyuantongyu** [THU-LYJ-Lab/AR-Seg#3]
In `evaluation.py` you wrote

```python3
from dataset.camvid import CamVid, CamVidWithFlow
from dataset.cityscapes import CityScapes, CityScapesWithFlow
```
but there's no `dataset` folder in the repo.

**Comment by AlbertHuyb** [comment]
Thanks for pointing this out. It has been updated.

**Comment by AlbertHuyb** [comment]
I'm going to close this issue. Welcome to star this repo if you find it helpful.
