### ISSUE TITLE
No `workspace-cityscapes/test_001.bin` file exists.

### ISSUE THREAD

**Issue by iris0329** [THU-LYJ-Lab/AR-Seg#4]
Hi author, thanks for your excellent work and open source.

When running the file `generate_compressed_dataset_cityscapes.py` to [this line](https://github.com/THU-LYJ-Lab/AR-Seg/blob/main/pre-process/generate_compressed_dataset_cityscapes.py#L16)

it reports an error that `no workspace-cityscapes/test_001.bin file exists.` I didn't find a related file about this `/test_001.bin`. 

Could you tell me how to find the `test_001.bin` file?

**Comment by AlbertHuyb** [comment]
`test_001.bin` is the middle file which stores motion vectors decoded from the videos.

Could you please check if there are errors during the video decoding process?

The video decoding is executed [here.](https://github.com/THU-LYJ-Lab/AR-Seg/blob/main/pre-process/generate_compressed_dataset_cityscapes.py#L172)

**Comment by iris0329** [comment]
Ah, I see, many thanks!

it is because there is no `libx265.so.198` and `liblibde265.so`. 

my solution is to 
```
find ./ -name libx265.so.198
find ./ -name liblibde265.so
```

and add the found dir (not file path) to `LD_LIBRARY_PATH`
