### ISSUE TITLE
requirements.txt中克隆项目报错

### ISSUE THREAD

**Issue by Vickywhy** [THU-LYJ-Lab/AR-Seg#6]
你好，我在运行requirements文件时出现如下报错，是什么问题呢
Collecting git+https://github.com/zzd1992/Image-Local-Attention.git@master (from -r requirements.txt (line 7))
  Cloning https://github.com/zzd1992/Image-Local-Attention.git (to revision master) to /tmp/pip-req-build-u46ruy3g
  Running command git clone -q https://github.com/zzd1992/Image-Local-Attention.git /tmp/pip-req-build-u46ruy3g
  Resolved https://github.com/zzd1992/Image-Local-Attention.git to commit a4020b9b3bb2b7eeca91adcd829cceb0491e2a66
    ERROR: Command errored out with exit status 1:
     command: /home/WA22201024/anaconda3/envs/AR-Seg/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-u46ruy3g/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-u46ruy3g/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d9qe5al3
         cwd: /tmp/pip-req-build-u46ruy3g/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-u46ruy3g/setup.py", line 1, in <module>
        from torch import cuda
      File "/home/WA22201024/anaconda3/envs/AR-Seg/lib/python3.6/site-packages/torch/__init__.py", line 189, in <module>
        _load_global_deps()
      File "/home/WA22201024/anaconda3/envs/AR-Seg/lib/python3.6/site-packages/torch/__init__.py", line 142, in _load_global_deps
        ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
      File "/home/WA22201024/anaconda3/envs/AR-Seg/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/WA22201024/anaconda3/envs/AR-Seg/lib/python3.6/site-packages/torch/lib/../../../../libcublas.so.11: symbol free_gemm_select version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
    ----------------------------------------
WARNING: Discarding git+https://github.com/zzd1992/Image-Local-Attention.git@master. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by AlbertHuyb** [comment]
It seems like issues related to your cuda installation. Please check your cuda toolkits.

**Comment by Vickywhy** [comment]
> It seems like issues related to your cuda installation. Please check your cuda toolkits.

First，thanks for your answer.
but，I have done conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=11.0 -c pytorch
and in the environment configuration file the cuda pointed to is the cuda11.3 installed on the server，like this
export PATH=$PATH:/usr/local/cuda-11.3/bin
export CUDA_TOOLKIT_ROOT_DIR="/usr/local/cuda-11.3"
export CUDA_INCLUDE_DIRS="/usr/local/cuda-11.3/include"
export CUDA_CUDART_LIBRARY="/usr/local/cuda-11.3/lib64"
export LD_LIBRARY_PATH="/usr/local/cuda-11.3/lib64:$LD_LIBRARY_PATH"
export CUDA_HOME=/usr/local/cuda-11.3
I am a non root user of the server， do I need to install my own cuda in my own directory？

**Comment by AlbertHuyb** [comment]
The errors come from installing the Image-Local-Attention package unsucessfully.
You can try to install the package with `git clone https://github.com/zzd1992/Image-Local-Attention.git` and `python setup.py install`.
Based on the logged information, perhaps you can find the solutions.
