### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by thundercult** [THU-LYJ-Lab/AR-Seg#8]
In the step where I ran 'python ./generate_compressed_dataset_camvid.py,' I encountered the following issue. Is it due to incorrect path settings on my part or a lack of packages for handling videos, such as x265 and dec265?

```
./workspace-camvid//proxy_3000.hevc: No such file or directory
cp: cannot stat './workspace-camvid/decoded-001.png': No such file or directory
cp: cannot stat './workspace-camvid/decoded-001.png': No such file or directory
ln: failed to create symbolic link './workspace-camvid//x265': No such file or directory
ln: failed to create symbolic link './workspace-camvid//dec265': No such file or directory
ln: failed to create symbolic link './workspace-camvid/000.png': No such file or directory
ln: failed to create symbolic link './workspace-camvid/001.png': No such file or directory
.......
```

**Comment by AlbertHuyb** [comment]
Please check if [this line](https://github.com/THU-LYJ-Lab/AR-Seg/blob/main/pre-process/generate_compressed_dataset_camvid.py#L231) works properly. 

You can copy the command and run it in the command line to see if it raises any error info.

If this line doesn't run correctly, then you should check the x265 installation. Please check [readme ](https://github.com/THU-LYJ-Lab/AR-Seg/blob/main/pre-process/README.md)under the pre-process folder.

Welcom to star this repo if you find it helpful. :)

**Comment by thundercult** [comment]
Thank you for your patient reply.
After I completed the installation of packages such as x265, the following error occurred
`Could find no file with path './workspace-camvid//%03d.png' and index in the range 0-4
./workspace-camvid//%03d.png: No such file or directory`
After I found the location of the error(I'm not sure if it's the right place),In 222 lines`encode_cmd = "ffmpeg -y -i %s"%workspace_dir+"/%03d.png -f rawvideo -pix_fmt yuv420p "+os.path.join(workspace_dir,"proxy.yuv")`I wonder if %03d here is not assigned？

**Comment by AlbertHuyb** [comment]
You can try to execute the encode and decode command in cmd separately and observe the log infos.

`%03d` here don't need to be assigned as it is part of ffmpeg commands that specifies the input image frames.

**Comment by umarjibrilmohd** [comment]
i"m facing challenge with installing these. opencv-python==4.5.5.62
git+https://github.com/zzd1992/Image-Local-Attention.git@master

**Comment by HychaoWang** [comment]
Hi. I follow the readme in pre-process and install the x265. But i still get errors like 

> ./workspace-camvid/proxy_3000.hevc: No such file or directory

 when running `python ./generate_compressed_dataset_camvid.py`

**Comment by AlbertHuyb** [comment]
> Hi. I follow the readme in pre-process and install the x265. But i still get errors like
> 
> > ./workspace-camvid/proxy_3000.hevc: No such file or directory
> 
> when running `python ./generate_compressed_dataset_camvid.py`

@HychaoWang This happends when the pre-process scripts exit with errors. As the ffmpeg program may log a lot of lines, you may miss the error messages. So I still suggest that you can try to execute the encode and decode command in cmd separately and observe the log infos. The commands locate at [L222](https://github.com/THU-LYJ-Lab/AR-Seg/blob/main/pre-process/generate_compressed_dataset_camvid.py#L222), [L231](https://github.com/THU-LYJ-Lab/AR-Seg/blob/main/pre-process/generate_compressed_dataset_camvid.py#L231), [L242](https://github.com/THU-LYJ-Lab/AR-Seg/blob/main/pre-process/generate_compressed_dataset_camvid.py#L242C21-L242C21) and [L246](https://github.com/THU-LYJ-Lab/AR-Seg/blob/main/pre-process/generate_compressed_dataset_camvid.py#L246).

You can check these commands by print them in the python script, then paste them to command line, and run them one-by-one to figure out the specific issues in your environment settings.
